channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=23.3.1
- pip:
  - mlflow==2.11.3
  - cffi==1.16.0
  - click==8.1.7
  - cloudpickle==2.2.1
  - distributed==2023.7.0
  - graphviz==0.20.1
  - importlib-metadata==5.2.0
  - jinja2==3.1.2
  - matplotlib==3.6.0
  - numpy==1.25.2
  - packaging==21.3
  - pandas==1.5.3
  - pyarrow==6.0.1
  - pycaret==3.2.0
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
